version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build(deps-dev)'
    labels:
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build(deps-dev)'
    labels:
      - 'dependencies'
    versioning-strategy: increase-if-necessary
