version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build(deps-dev)'
    labels:
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'jest'
      - dependency-name: 'ts-jest'
      - dependency-name: '@jest*'
    commit-message:
      prefix: 'build(deps-dev)'
    labels:
      - 'dependencies'
    versioning-strategy: increase-if-necessary
